#!/usr/bin/env node

var fs = require('fs');
var http = require('http');
var mime = require('mime');
var path = require('path');
var url = require('url');
var ws = require('ws');
const ps = require('child_process');

const CONFIG = require(path.join('..', 'config.json'));
ps.exec('npm start')

const IMG_PATH = path.join(__dirname, '/canvas.png');

const Canvas = require('./Canvas');
const {
	getColorId,
	colors,
	OPCODES,
	compress,
	decompress
} = require('./utils');

// function is just for awaits
async function start() {
	let canvas = new Canvas();
	await canvas.load(fs.existsSync(IMG_PATH) ? IMG_PATH : null);

	setInterval(function () {
		let {
			heapTotal,
			heapUsed
		} = process.memoryUsage();
		console.log(`Memory total: ${heapTotal/10000000}MB. Memory used: ${heapUsed/10000000}MB.`);
		console.log(`Canvas size: ${canvas.width}x${canvas.height}`);
		console.log('-------------------------')
	}, 10000)

	var sessions = {};
	var connections = [];
	var socket = ws.createServer({
		port: 3939
	});
	socket.on('connection', function (connection) {
		var id = connection.upgradeReq.headers['x-forwarded-for'];
		if (id == null) {
			id = connection.upgradeReq.socket.remoteAddress;
		}
		console.log(id)

		connection.id = id;
		connection.session = (sessions[id] = sessions[id] || {
			wait: 0,
		});

		if (connection.session.wait > Date.now()) {
			try {
				let dv = new DataView(1 + 8);
				dv.setUint8(OPCODES.COOLDOWN);
				dv.setFloat64(connection.session.wait);

				connection.send(dv);
			} catch (error) {
				console.error(error);
			}
		}

		connections.push(connection);
		connection.on('message', function (data, flags) {
			if (flags.binary) {
				let dv = new DataView(data.buffer, data.byteOffset, data.byteLength);
				switch (dv.getUint8(0)) {
					case OPCODES.PIXEL: {
						if (connection.session.wait > Date.now()) return

						let x = dv.getUint16(1);
						let y = dv.getUint16(3);

						if (x >= canvas.width || y >= canvas.height || x < 0 || y < 0) {
							return;
						}

						const colorId = dv.getUint8(5);
						if (colorId < 0 || colorId >= colors.length) return;

						canvas.setPixel(x, y, colorId);

						connections.forEach(function (connection) {
							try {
								connection.send(data);
							} catch (error) {
								console.error(error);
							}
						});

						var factor = Math.sin((x * 0.5) + (y * 0.5));
						var duration = Math.abs(factor) * 8192 * Math.min(100, connections.length / 100);

						if (connection.session.isAdmin) {
							connection.session.wait = 0;
						} else {
							connection.session.wait = Date.now() + Math.max(CONFIG.cooldown*1000, Math.floor(duration));
						}

						dv = new DataView(new ArrayBuffer(1 + 8));
						dv.setUint8(0, OPCODES.COOLDOWN);
						dv.setFloat64(1, connection.session.wait);

						connection.send(dv.buffer);
						break
					}
				}
			}else{
				console.log('Text message: ' + data)
				connection.session.isAdmin = true;
			}
		});

		connection.on('close', function () {
			connections.splice(connections.indexOf(connection), 1);
		});

		let pixelData = canvas.data; //canvas.toBuffer();
		let compressed = compress(pixelData);
		const badCompression = (compressed.length > pixelData.length);
		let data
		if (badCompression) {
			data = new Uint8Array(pixelData.length + 10);
		} else {
			data = new Int8Array(compressed.length + 10);
		}

		let view = new DataView(data.buffer, data.byteOffset, data.byteLength);

		view.setUint8(0, OPCODES.BOARD);
		view.setUint8(1, badCompression ? 0 : 1);

		view.setUint16(2, 0);
		view.setUint16(4, 0);
		view.setUint16(6, canvas.width);
		view.setUint16(8, canvas.height);

		data.set(badCompression ? pixelData : compressed, 10);

		try {
			connection.send(data);
		} catch (error) {
			console.error(error);
		}
	});

	setTimeout(function callback(then, cooldown, delay) {
		var now = Date.now();
		var time = now - then;

		if (connections.length > 0) {
			cooldown -= time;
		}

		if (cooldown <= 0) {
			cooldown = cooldown + delay;

			canvas.expand(CONFIG.expandSize);
			let pixelData = canvas.data; //canvas.toBuffer();
			let compressed = compress(pixelData);
			console.log(pixelData.length, decompress(compressed).length)
			fs.writeFileSync('test', [...pixelData, '\n', ...compressed].join(','))
			const badCompression = (compressed.length > pixelData.length);
			let data
			if (badCompression) {
				data = new Uint8Array(pixelData.length + 10);
			} else {
				data = new Int8Array(compressed.length + 10);
			}

			let view = new DataView(data.buffer, data.byteOffset, data.byteLength);

			view.setUint8(0, OPCODES.BOARD);
			view.setUint8(1, badCompression ? 0 : 1);

			view.setUint16(2, 0);
			view.setUint16(4, 0);
			view.setUint16(6, canvas.width);
			view.setUint16(8, canvas.height);

			data.set(badCompression ? pixelData : compressed, 10);


			connections.forEach(function (connection) {
				try {
					connection.send(data);
				} catch (error) {
					console.error(error);
				}
			});
		}

		canvas.save(IMG_PATH).then(function () {
			setTimeout(callback, CONFIG.expandRate * 1000, now, cooldown, delay);
		})
	}, 0, Date.now(), CONFIG.expandRate * 1000, CONFIG.expandRate * 1000);
}
start();